#!/bin/bash
## Download comics by name from readcomiconline

# set up our variables
name=$3
url='https://readcomiconline.li/Comic/'
zip='--zip'
dir='-d ./'
# Change the cookies to a relative link?
cookies='--cookies /mnt/es3/media/comiclib/cookies-readcomiconline-li.txt'
sleep='--sleep 1'
chapter='--chapter-range '$1'-'$2

# run the command
gallery-dl $sleep $cookies $dir $chapter $url$name
