#!/bin/bash

for cbr in *.cbr
do
  dirname=`echo $cbr | sed 's/\.cbr$//'`
  if mkdir "$dirname"
  then
    if cd "$dirname"
    then
      unrar e ../"$cbr" 
      rm zSoU-Nerd.jpg
	  rm zWater.jpg
	  rm ZZZZZ.jpg
	  rm zzzzz.jpg
	  rm zzzg7.jpg
	  cd ..
      rm -f $cbr # Uncomment to delete the original cbr file
    else
      echo "Could not unpack $cbr - cd failed"
    fi
  else
    echo "Could not unpack $cbr - mkdir failed"
  fi
done
